trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Install Python 3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    # Secret variables are mapped here to avoid cyclical references
    pytest tests/
  displayName: 'Run LambdaTest Appium Tests'
  env:
    # Map the secret variables from the ADO UI/Library to environment variables
    LT_USERNAME: $(LT_USERNAME)
    LT_ACCESS_KEY: $(LT_ACCESS_KEY)
